apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-mysql
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.database.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql