name: Manage AKS with Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action (apply or destroy)"
        required: true
        default: "apply"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      uses: dflook/terraform-init@v1
      with:
        path: ./az_tf

    - name: Terraform Plan
      if: github.event.inputs.action == 'apply'
      uses: dflook/terraform-plan@v1
      with:
        path: ./az_tf

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      uses: dflook/terraform-apply@v1
      with:
        path: ./az_tf
        auto_approve: true

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      uses: dflook/terraform-destroy@v1
      with:
        path: ./az_tf
        auto_approve: true

    - name: Terraform Output
      uses: dflook/terraform-output@v1
      with:
        path: ./az_tf
