name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        uses: dflook/terraform-init@v1
        with:
          path: ./az_tf

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        uses: dflook/terraform-plan@v1
        with:
          path: ./az_tf

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        uses: dflook/terraform-apply@v1
        with:
          path: ./az_tf

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        uses: dflook/terraform-destroy@v1
        with:
          path: ./az_tf

      - name: Terraform Output
        if: github.event.inputs.action == 'apply'
        uses: dflook/terraform-output@v1
        with:
          path: ./az_tf